services:
  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile
    container_name: llm_service
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gemini-flash-lite-latest}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COLLECTION_NAME=${COLLECTION_NAME:-my_collection}
      - EMBEDDINGS_MODEL=${EMBEDDINGS_MODEL:-sentence-transformers/all-mpnet-base-v2}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_HOST=${QDRANT_HOST:-qdrant}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - USER_AGENT=${USER_AGENT:-myagent}
    volumes:
      - ${PWD}/documents:/app/documents
    ports:
      - "80:8001"
    networks:
      - agentic-net

networks:
  agentic-net:
    driver: bridge
